apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}

        envFrom:
        - configMapRef:
            name: col-cfg

        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        - name: schema-volume
          mountPath: /docker-entrypoint-initdb.d/

      volumes:
      - name: schema-volume
        configMap:
          name: mariadb-schema

  volumeClaimTemplates:
  - metadata:
      name: mariadb-storage
    spec:
      storageClassName: nfs-client
      accessModes:
        - ReadWriteMany    # Change to RWO if required
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  clusterIP: None
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
