apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-deploy
spec:
  serviceName: mariadb
  replicas: 3
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: mariadb:10.5
        ports:
        - containerPort: 3306

        envFrom:
        - configMapRef:
            name: col-cfg

        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        - name: schema-volume
          mountPath: /docker-entrypoint-initdb.d/

      volumes:
      - name: schema-volume
        configMap:
          name: mariadb-schema

  volumeClaimTemplates:
  - metadata:
      name: mariadb-storage
    spec:
      storageClassName: nfs-client-mariadb
      accessModes:
        - ReadWriteMany    # Change to RWO if required
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: maria
spec:
  clusterIP: None
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
