version: '3.8'

services:
  collage-portal:
    build: public/college-portal/Dockerfile
    container_name: c
    ports:
      - "81:3000"
    environment:
      - .env 
    volumes:
      - "collage"

volumes:
  - {}