version: '3.8'

services:
  collage-portal:
    build: /home/ubuntu/Duniversity-College-Portal/public/college-portal
    container_name: c-p
    ports:
      - "81:3000"
    env_file:
      - ./.env 
    depends_on:
      - data-base
    
  data-base:
    image: mysql:8.0
    container_name: data
    env_file:
      - ./.env
    ports:
      - "3306:3306"

    volumes:
      - data1:/var/lib/data1

volumes:
  data1: {}







